import Head from "next/head";
import { Box } from "@chakra-ui/react";
import Upload from "../components/Upload";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Fotoin</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box>
				<Upload />
			</Box>
		</div>
	);
}
